# customer-service Dockerfile
FROM eclipse-temurin:23-jdk-alpine

WORKDIR /app

COPY target/customer-service-0.0.1-SNAPSHOT.jar customer-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "customer-service-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080